package io.ably.jmeter;

public interface Constants {
	String ENVIRONMENT = "ably.environment";
	String SSE_CLIENT = "ably.sse_client";
	String SSE_CLIENT_HANDLER = "ably.sse_client_handler";
	String REALTIME_CLIENT = "ably.realtime_client";
	String REALTIME_CLIENT_GROUP = "ably.realtime_client_group";
	String REST_CLIENT = "ably.rest_client";
	String API_KEY = "ably.api_key";
	String CLIENT_ID = "ably.client_id";
	String CLIENT_ID_GROUP = "ably.client_id_group";
	String CLIENT_ID_PREFIX = "ably.client_id_prefix";
	String CLIENT_ID_SUFFIX = "ably.client_id_suffix";
	String MESSAGE_TYPE = "ably.message_type";
	String MESSAGE_FIX_LENGTH = "ably.message_type_fixed_length";
	String MESSAGE_TO_BE_SENT = "ably.message_to_send";
	String MESSAGE_EVENT_NAME = "ably.message_event_name";
	String MESSAGE_ENCODING = "ably.message_encoding";
	String CHANNEL_NAME = "ably.channel_name";
	String CHANNEL_NAME_PREFIX = "ably.channel_name_prefix";
	String CHANNEL_NAME_SUFFIX = "ably.channel_name_suffix";
	String CHANNEL_PARAMS = "ably.channel_params";
	String ADD_TIMESTAMP = "ably.add_timestamp";
	String SAMPLE_CONDITION_VALUE = "ably.sample_condition_value";
	String SAMPLE_CONDITION = "ably.sample_condition";
	String DEBUG_RESPONSE = "ably.debug_response";
	String MESSAGE_TYPE_RANDOM_STR_WITH_FIX_LEN = "Random string with fixed length";
	String MESSAGE_TYPE_HEX_STRING = "Hex string";
	String MESSAGE_TYPE_STRING = "String";
	String SAMPLE_ON_CONDITION_OPTION1 = "specified elapsed time (ms)";
	String SAMPLE_ON_CONDITION_OPTION2 = "number of received messages";
	String STATS_START = "ably.stats_start";
	String STATS_END = "ably.stats_end";
	String STATS_LIMIT = "ably.stats_limit";
	String STATS_UNIT = "ably.stats_unit";
	String UNITS = "minute,hour,day,month";
	String HISTORY_START = "ably.history_start";
	String HISTORY_END = "ably.history_end";
	String HISTORY_LIMIT = "ably.history_limit";
	String STATS_DIRECTION = "ably.stats_direction";
	String HISTORY_DIRECTION = "ably.history_direction";
	String DIRECTIONS = "backwards,forwards";
	String LOG_LEVEL = "ably.log_level";
	String GROUP_SIZE = "ably.group_size";
	int MAX_RANDOM_ID_LENGTH = 32;
	String DEFAULT_ENVIRONMENT = "${ably.environment}";
	String DEFAULT_API_KEY = "${ably.api_key}";
	String DEFAULT_CHANNEL_NAME_PREFIX = "test_channel";
	String DEFAULT_EVENT_NAME = "test-event";
	String DEFAULT_ENCODING = "";
	String DEFAULT_CLIENTID = "client";
	int DEFAULT_SAMPLE_VALUE_COUNT = 1;
	int DEFAULT_SAMPLE_VALUE_ELAPSED_TIME_MILLI_SEC = 1000;
	String DEFAULT_MESSAGE_FIX_LENGTH = "1024";
	String DEFAULT_STATS_START = "${TESTSTART.MS}";
	String DEFAULT_STATS_END = "";
	String DEFAULT_STATS_LIMIT = "10";
	String DEFAULT_HISTORY_START = "${TESTSTART.MS}";
	String DEFAULT_HISTORY_END = "";
	String DEFAULT_HISTORY_LIMIT = "100";
	int DEFAULT_GROUP_SIZE = 32;
	int DEFAULT_LOG_LEVEL = 4; // WARN
	int DEFAULT_UNIT = 0; // minute
	int DEFAULT_STATS_DIRECTION = 0; // backwards
	int DEFAULT_HISTORY_DIRECTION = 0; // backwards
	boolean DEFAULT_ADD_CLIENT_ID_SUFFIX = true;
	boolean DEFAULT_ADD_CHANNEL_NAME_SUFFIX = false;
	int SUB_FAIL_PENALTY = 1000; // force to delay 1s if sub fails for whatever reason
}
